### ISSUE TITLE
<WS session Ingress host URL> is not available yet (Operator)

### ISSUE THREAD

**Issue by askarbozcan** [eclipsesource/theia-cloud#150]
Problem: Operator cannot set the URL for Session Spec. Due to this, after IDE pod is created, the landing page is stuck on "preparing the session"

Thinned it down to the following error in operator pod logs:
`ERROR org.eclipse.theia.cloud.operator.handler.impl.AddedHandlerUtil - [16695cf8-1e88-4ca9-93b2-483ebb89e5e4] ws.theia.io/e91be8be-0ed3-4c81-8a7b-b3d03bad6fd2/ is NOT available yet.`

This later on propagates to the Service which times out, as it wait for the spec to have a url.

The thing is, the Theia instance IS available, and ingress works fine. 
So, I was wondering what could the problem.

Notes: ws.theia.io is the URL I set for ingress. I am running Theia Cloud locally inside a Docker Desktop k8s cluster and all the URLs used route to localhost with /etc/hosts.

**Comment by askarbozcan** [comment]
Looks like could be the duplicate of #147

**Comment by lucas-koehler** [comment]
Quick question. What do you mean with the ingress works fine? Could you access the instance by directly going to the URL in the browser?

**Comment by askarbozcan** [comment]
Yes, exactly.

**Comment by lucas-koehler** [comment]
Alright, which OS are you running the cluster on? Locally, we have only tested this on Minikube on Linux. I know that other people had issues on Minikube on Mac and Windows due to some DNS issues.
Could you also tell us what version of the helm chart and theia cloud images you are using?

**Comment by askarbozcan** [comment]
Absolutely. Sorry for not giving enough info in the first place.

OS: MacOS Monterey, 12.6
k8s handler: Docker Desktop v4.4.2
k8s version: v1.22.5
Chart version: version: 0.7.8
Theia cloud images version: 0.8.0.MS8

**Comment by lucas-koehler** [comment]
Hi @askarbozcan , thanks for additional details.
After a discussion with the team today we figured that the problem might be DNS inside your cluster. As the pod is reachable from the outside via its normal address, the pod and the ingress must work correctly. Thus, the problem could be that the operator cannot resolve the pod's address (e.g.  ws.theia.io/e91be8be-0ed3-4c81-8a7b-b3d03bad6fd2/) to the IP address of the cluster.
To test this, you could launch a session and then afterwards launch another pod with a shell and try to access the pod (e.g. using wget or curl). If this doesn't work that is a strong indicator that dns is wrong.

A concrete idea what could be the issue is that you mapped ws.theia.io in you /etc/hosts file. Probably, you'd also need to do that in the cluster's hosts configuration. Did you do this?

**Comment by askarbozcan** [comment]
After discussing this issue with my colleagues, we arrived at the conclusion that using ingress hostnames (locally) won't work in non-Linux environments due to VM utilized by Docker in non-Linux systems.

Containers inherit their hosts' DNS settings, which in non-Linux Docker case means the VM's DNS settings.

I think this issue can be closed, and a note added to docs.
